### ISSUE TITLE
Specify video quality

### ISSUE THREAD

**Issue by waz1500** [DevLARLEY/wingfox-downloader#2]
I'm wondering if there is currently or will be a way to specify the video quality when using main.py? The files being produced create 360p videos but I know there is a 720p version available on the site.

**Comment by DevLARLEY** [comment]
It's probably happening because the standard quality is 360p and a cookie is set when selecting higher qualities. (The case with iq.com)
I can't implement a solution for that right now because all of the course previews are only 360p.

**Comment by waz1500** [comment]
I did find a few courses with trailers that are in 720p and are viewable without a login. Are you able to try: `wingfox.com/c/9403/256290`
There's also `wingfox.com/c/9146/201779` and `wingfox.com/c/9406/256331` that I've also found. They should be viewable without an account and some of them offer a free lecture with one.

**Comment by DevLARLEY** [comment]
That should be easy...
I found multiple URLs inside the video JSON:
```json
"hls": [
    "https://hls.videocc.net/9215d65496/c/9215d65496b32be2d6bd8decffe3577c_1.pdx",
    "https://hls.videocc.net/9215d65496/c/9215d65496b32be2d6bd8decffe3577c_2.pdx",
    "https://hls.videocc.net/9215d65496/c/9215d65496b32be2d6bd8decffe3577c_3.pdx"
  ]
```

So I'll implement that when I have the time

**Comment by DevLARLEY** [comment]
I updated main.py, the script should now always download the highest quality

**Comment by waz1500** [comment]
Confirmed working here! Thank you for this update.

It's interesting that the three streams provided on the site player are labelled `360p`, `480p`, and `720p`, However, with the new update, it grabbed highest quality stream out of the three but checking it's properties it's clearly `1080p`. They perhaps never updated the infographics on the site player. 
```
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
```
