### ISSUE TITLE
Subtitles not detected

### ISSUE THREAD

**Issue by waz1500** [DevLARLEY/wingfox-downloader#4]
I noticed the subtitles are not currently being detected and I'm wondering if they could be downloaded in addition to the video.

This can be seen on the trailer video for `wingfox.com/c/8603/175004`

Usually there are burned in subtitles depending on the speaker's native language (Chinese, English etc), and then on top English subtitles that can be enabled or disabled using the cog feature on the site player. It looks like the player is conveniently positioning the on the fly subtitles above where the native language is. 

`Extracted, there are 1 streams, with 1 basic streams, 0 audio streams, 0 subtitle streams`

**Comment by DevLARLEY** [comment]
Haven't had the time to take a look, but I hope the subtitles are unencrypted...

**Comment by DevLARLEY** [comment]
I updated the script. Subtitles should be saved now

**Comment by waz1500** [comment]
Amazing work! I wasn't expecting an update so soon!
By default the subtitles do overlap with the native burned in translation, but since .srt files don't contain positional data, a simple subtitle offset on any media player works and is what I suspected was happening on the site player. 

I am using `--output` to specify a new directory along with an output name such as this. `--output 'D:\wing\test\file.mp4'`. It does move the video but not the subtitle. 

Would it be possible to have the subtitles follow the `--output` location in addition to the video? Perhaps even the naming of the video or was the flag ideally meant to be just the output file name only?

**Comment by DevLARLEY** [comment]
Updated the script again:
+ subtitles are moved to the file directory
+ specified directory will be ceated, if it doesn't exist
+ video names are taken from the video json if not specified manually

**Comment by waz1500** [comment]
I have tried the newest version of the script but it no longer grabs the subtitles. It creates the video file only even if subtitles are available. 

Old version:
```
[INFO]: Decrypting fragment ...
[INFO]: Muxing all segments...
[INFO]: Saving subtitle English...
```

Newest version:
```
[INFO]: Decrypting fragment ...
[INFO]: Muxing all segments...
```

**Comment by DevLARLEY** [comment]
I'll fix it when I have the time, but try specifying a relative output path like: download/video.mkv
I was only testing it with relative paths, so maybe soecifying something else breaks it

**Comment by waz1500** [comment]
Thanks! 
I did try a relative output path as suggested but it still didn't grab the subtitle. I've also tried not using the the `--output` flag at all and it also didn't download the subs. 
`--output 'downloads\video.mkv'` 
 `--output 'c:\newfolder\video.mkv'`

**Comment by DevLARLEY** [comment]
Haha, just realized, that i had forgotten to connect the new --subtitles option to the actual method, so try again with --subtitles appended
Before, it would just always try to download subtitles

**Comment by waz1500** [comment]
Yay! Appending `--subtitles` in addition to `--output` worked.
I can understand having it as a separate flag for people who don't want to download subs. 
Thanks for letting me know!
