### ISSUE TITLE
Unable to parse option value "NaN" as video rate

### ISSUE THREAD

**Issue by waz1500** [DevLARLEY/wingfox-downloader#5]
I'm getting the following demuxer error on certain videos. Not sure what is causing it as it managed to grab the videos prior just fine. The videos are also playing fine on the site player. They have a much longer video duration and therefore have a lot of fragments. I know the script has only been tested on short duration trailers. 

I'm using node-v22.6.0, python-3.12.5 and ffmpeg version 2024-08-07-git-94165d1b79. 

```
[image2 demuxer @ 0000023baa6e5180] Unable to parse option value "NaN" as video rate
[image2 demuxer @ 0000023baa6e5180] Error setting option framerate to value NaN.
[in#0 @ 0000023baa6e4bc0] Error opening input: Invalid argument
```
Let me know if there is anything else I can provide.

**Comment by DevLARLEY** [comment]
Some questions:
+ How many fragments does the video have? This should be displayed by N_m3u8DL-RE after downloading. (Aka. was this the last fragment?)
+ What's the debug ouptut of the program when it starts? (The one that says seed_const at the start, plus the two lines after)
+ Is there a preview that makes this error occur or does this only happen on longer videos?

The error seems to only originate from javascript returning an invalid framerate ("NaN") on the (hopefully, don't know yet) last fragment (or even last frame?)

**Comment by waz1500** [comment]
1. According to the output there are 198 Segments and the error occurs on fragment 197.
2. See below
3. It's just the longer videos but on this particular course that I'm finding the error on. I don't have many so it's difficult to replicate. I can send over my cookie via email if you would like to test further on your end. I will test on videos past this one to see if the error still occurs.   
```
seed_const => 159
hlsLevel => app
hlsPrivate => 1
...
INFO : Extracted, there are 1 streams, with 1 basic streams, 0 audio streams, 0 subtitle streams
INFO : Vid Kbps | 198 Segments | ~32m40s
INFO : Selected streams:
INFO : Vid Kbps | 198 Segments | ~32m40s
WARN : Writing meta json
...
```

**Comment by DevLARLEY** [comment]
Don't send the cookie _yet_, as I'm not home. You can send me a message to my alt account: k6idalt@gmail.com when I'm home. (I'll post an update here)

**Comment by waz1500** [comment]
I've sent some info to your email. Due to time zones, I'll be offline until the morning but I'll keep an eye on the github page for any updates. I hope it is useful and you are able to identify what it causing the issue.

**Comment by DevLARLEY** [comment]
The issue seems to be that the last fragment only contains a single frame. A pretty lame error

EDIT: I've solved the issue and testing the changes right now, but decoding 197 fragments on an i5-8265U (my laptop) isn't that fast (40min). And it's also 1am

EDIT2: Tested, works. Also pushed the public update

**Comment by waz1500** [comment]
That's really surprising. I do wonder if there are more videos that contain a single frame on the last fragment or perhaps this particular video was a special case. 

Tested with the new update and also confirmed working. Thank you! This update is very much appreciated.
