### ISSUE TITLE
Subtitle error can't encode character

### ISSUE THREAD

**Issue by waz1500** [DevLARLEY/wingfox-downloader#6]
The script was updated recently so that video and subtitle names are taken from the video json if not specified manually. This is what I am using in my prompt by not specifying the output name and location. 
`python .\main.py --id xxxxx --cookie xxx --subtitles`
The video name is saved as per the json such as this `12:简化测试.mp4_2503`. However this particular subtitle won't save and breaks main.py

I'm wondering if it's the Chinese Simplified text that is causing issues or a particular ascii within the actual .srt file that is causing trouble. Most likely the Ideographic Comma that is commonly used in grammar. 

```
[INFO]: Muxing all segments...
[INFO]: Saving subtitle English...
Traceback (most recent call last):
  File "C:\Users\test\Desktop\wing\main.py", line 397, in <module>
    dl.save_subtitles(
  File "C:\Users\test\Desktop\wing\main.py", line 262, in save_subtitles
    ).write(srt_request.text)
      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u3001' in position 17975: character maps to <undefined>
```

**Comment by DevLARLEY** [comment]
Oops, didn't specify an encoding. Change:
"w"
to:
"w",
encoding="utf-8"

**Comment by waz1500** [comment]
Confirmed working after making the edits. Subtitle was able to download. Thanks!

**Comment by DevLARLEY** [comment]
I'll update the downloader from my phone haha
