### ISSUE TITLE
Decrypting fragment error

### ISSUE THREAD

**Issue by Jeyamir** [DevLARLEY/wingfox-downloader#7]
Getting the following error on last fragment of the video. There has been a few. Other than that all working fine. Thank you for this great tool.

I'm on linux environment
....
[mpegts @ 0x4760170] nothing to probe for stream 2
[DEBUG]: node decrypt_2.js /home/..../wingfox-downloader/249833/0/47.ts fragment_47.mkv 00e1d476ef4dd8ae47e3b54e6a24b4583038f33efeb0af88e1efc3c9b7e62f98 b6ac0fe25dbfb06e75090aed917158a1 05503d1c-0f3e-4b12-9d6b-bcb0e1d6abf4-a128932 170 47
[INFO]: Decrypting fragment 48...
[mpegts @ 0x41cfc50] decoding for stream 0 failed
[mpegts @ 0x41cfc50] Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
fragment_48.aac: End of file
Error: Command failed: ffmpeg -hide_banner -loglevel error -y -i fragment_48.mp4 -i fragment_48.aac -codec copy fragment_48.mkv
fragment_48.aac: End of file

/home/jeyamir/wingfox-downloader/lib_player_2.js:5300
  throw "abort(" + what + "). Build with -s ASSERTIONS=1 for more info."
  ^
abort(Error: Command failed: ffmpeg -hide_banner -loglevel error -y -i fragment_48.mp4 -i fragment_48.aac -codec copy fragment_48.mkv
fragment_48.aac: End of file
). Build with -s ASSERTIONS=1 for more info.
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v20.17.0
[ERROR]: Error while decrypting fragment

**Comment by DevLARLEY** [comment]
Could you upload the fragment that's causing the error?

**Comment by Jeyamir** [comment]
Hi, Good day to you. Please find the fragment that causing the issue. Thank you for your support. Regards
[48.zip](https://github.com/user-attachments/files/17301255/48.zip)

**Comment by DevLARLEY** [comment]
what's the URL of the video you're trying to download?

**Comment by Jeyamir** [comment]
Hi, thank you for the support. 
This video with it's last fragment having the issue.
The URL as follows:
https://www.wingfox.com/p/9248/249833

**Comment by DevLARLEY** [comment]
I don't have access to these course so you'll have to post your cookie here if you want me to take a look at it.
I was able to download the trailer and the first two episodes successfully though.

**Comment by Jeyamir** [comment]
Please note that only certain videos having this issue and all others are downloadable without any issue.
Thank you for the support.
The URL with cookie as follows:

python main.py --id 249833 --cookie hbrub4oofksd35d50v64reob0m --subtitles --debug

**Comment by DevLARLEY** [comment]
This is fixed as of https://github.com/DevLARLEY/wingfox-downloader/commit/304548a78cd8019161e801345f673991650da3b1 and https://github.com/DevLARLEY/wingfox-downloader/commit/68d83c41d884f6b58c141061f890a80bc9faf38e

**Comment by Jeyamir** [comment]
@DevLARLEY, I've successfully re-downloaded the other videos that having fragment issues without further issue.
Thank you for the support. Regards.
